[package]
name = "ciphersaber"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]

[[bin]]
name = "ciphersaber"
path = "ciphersaber.rs"

[dependencies.rpassword]
git = "https://github.com/BartMassey/rpassword"
branch = "tty"

[dependencies]
getopts = "*"
